# Generated by Django 2.2.5 on 2019-10-03 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Página Inicial',
                'verbose_name_plural': 'Página Inicial',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Título')),
                ('text', models.CharField(max_length=140, verbose_name='Texto')),
                ('hashtag', models.CharField(blank=True, max_length=20, verbose_name='Hastag')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagem de fundo')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel', to='sitemanager.HomePage')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Carousel',
            },
        ),
    ]
