# Generated by Django 2.2.5 on 2019-12-12 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0002_auto_20191121_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Parceiros',
                'verbose_name_plural': 'Parceiros',
            },
        ),
        migrations.CreateModel(
            name='PartnerSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel', to='sitemanager.PartnerPage')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Carousel',
            },
        ),
    ]
