# Generated by Django 2.2.5 on 2019-09-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0003_auto_20190926_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='hashtag',
            field=models.CharField(default='', max_length=20, verbose_name='Hastag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.FileField(default='', upload_to='', verbose_name='Imagem de fundo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='text',
            field=models.CharField(default='', max_length=140, verbose_name='Texto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
