# Generated by Django 2.2.5 on 2019-09-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0004_auto_20190926_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Página Inicial', 'verbose_name_plural': 'Página Inicial'},
        ),
        migrations.AlterField(
            model_name='slide',
            name='hashtag',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hastag'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagem de fundo'),
        ),
    ]
