# Generated by Django 2.2.5 on 2019-12-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0004_whowearepage_whoweareslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whowearepage',
            options={'verbose_name': 'Quem Somos', 'verbose_name_plural': 'Quem Somos'},
        ),
        migrations.AddField(
            model_name='partnerslide',
            name='title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whoweareslide',
            name='title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
