# Generated by Django 2.2.5 on 2019-12-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0005_auto_20191213_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='SphereImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Título')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagem')),
                ('thumb', models.ImageField(upload_to='', verbose_name='Thumb')),
            ],
            options={
                'verbose_name': 'Imagem 360',
                'verbose_name_plural': 'Imagens 360',
            },
        ),
    ]
