# Generated by Django 2.2.5 on 2019-12-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0006_sphereimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SphereVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Título')),
                ('url', models.URLField(verbose_name='Link do youtube')),
                ('thumb', models.ImageField(null=True, upload_to='', verbose_name='Thumb')),
            ],
            options={
                'verbose_name': 'Video 360',
                'verbose_name_plural': 'Videos 360',
            },
        ),
    ]
