# Generated by Django 2.2.3 on 2019-09-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stairwell', models.BooleanField(default=False)),
                ('cliff', models.BooleanField(default=False)),
                ('bay', models.BooleanField(default=False)),
                ('trail', models.BooleanField(default=False)),
                ('other', models.CharField(blank=True, default='', max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='BestTideMoves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.BooleanField(default=False)),
                ('high', models.BooleanField(default=False)),
                ('ebb', models.BooleanField(default=False)),
                ('flood', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dangers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=False)),
                ('localism', models.BooleanField(default=False)),
                ('boat', models.BooleanField(default=False)),
                ('jetski', models.BooleanField(default=False)),
                ('buoy', models.BooleanField(default=False)),
                ('pollution', models.BooleanField(default=False)),
                ('rock', models.BooleanField(default=False)),
                ('shark', models.BooleanField(default=False)),
                ('undertow', models.BooleanField(default=False)),
                ('other', models.CharField(blank=True, default='', max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='GroundPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rock', models.BooleanField(default=False)),
                ('sand', models.BooleanField(default=False)),
                ('coral', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SurfLevelNeeded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginner', models.BooleanField(default=False)),
                ('intermediate', models.BooleanField(default=False)),
                ('expert', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WaveDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.BooleanField(default=False)),
                ('left', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WaveFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.BooleanField(default=False)),
                ('regular', models.BooleanField(default=False)),
                ('high', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('car', models.BooleanField(default=False)),
                ('special_access', models.BooleanField(default=False)),
                ('beach_type', models.CharField(choices=[('Pública', 'Pública'), ('Privada', 'Privada')], max_length=100)),
                ('access_comment', models.TextField()),
                ('time_of_year', models.TextField()),
                ('good_day_description', models.TextField()),
                ('week_crowd', models.CharField(choices=[('Poucos Surfistas', 'Poucos Surfistas'), ('Muitos Surfistas', 'Muitos Surfistas')], max_length=50)),
                ('weekend_crowd', models.CharField(choices=[('Poucos Surfistas', 'Poucos Surfistas'), ('Muitos Surfistas', 'Muitos Surfistas')], max_length=50)),
                ('wave_quality', models.IntegerField()),
                ('wave_length', models.CharField(choices=[('Curta', 'Curta'), ('Longa', 'Longa'), ('Normal', 'Normal')], max_length=10)),
                ('wave_strength', models.CharField(choices=[('Potente', 'Potente'), ('Suave', 'Suave')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accesses', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.AccessPoint')),
                ('best_tide_moves', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.BestTideMoves')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='api.City')),
                ('dangers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Dangers')),
                ('grounds', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.GroundPoint')),
                ('surf_levels', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.SurfLevelNeeded')),
                ('wave_directions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.WaveDirection')),
                ('wave_frequencies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.WaveFrequency')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='api.State'),
        ),
    ]
