# Generated by Django 2.2.5 on 2019-10-03 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Texto')),
                ('preview_text', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lng', models.FloatField(verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='api.City', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Pico',
                'verbose_name_plural': 'Picos',
            },
        ),
        migrations.CreateModel(
            name='SpotDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to='', verbose_name='Imagem principal')),
                ('info_image', models.ImageField(upload_to='', verbose_name='Imagem lateral')),
                ('car', models.BooleanField(default=False, verbose_name='Acesso de carro')),
                ('special_access', models.BooleanField(default=False, verbose_name='Acesso especial')),
                ('beach_type', models.CharField(choices=[('Pública', 'Pública'), ('Privada', 'Privada')], max_length=100, verbose_name='Tipo de praia')),
                ('time_of_year', models.TextField(verbose_name='Melhor época do ano')),
                ('good_day_description', models.TextField(verbose_name='Dia bom')),
                ('access_comment', models.TextField(verbose_name='Comentário sobre o acesso')),
                ('week_crowd', models.CharField(choices=[('Poucos Surfistas', 'Poucos Surfistas'), ('Muitos Surfistas', 'Muitos Surfistas')], max_length=50, verbose_name='Crowd na semana')),
                ('weekend_crowd', models.CharField(choices=[('Poucos Surfistas', 'Poucos Surfistas'), ('Muitos Surfistas', 'Muitos Surfistas')], max_length=50, verbose_name='Crowd no final de semana')),
                ('wave_quality', models.IntegerField(verbose_name='Qualidade das ondas')),
                ('wave_length', models.CharField(choices=[('Curta', 'Curta'), ('Longa', 'Longa'), ('Normal', 'Normal')], max_length=10, verbose_name='Comprimento da onda')),
                ('wave_strength', models.CharField(choices=[('Potente', 'Potente'), ('Suave', 'Suave')], max_length=10, verbose_name='Força')),
                ('stairwell', models.BooleanField(default=False, verbose_name='Escadaria')),
                ('cliff', models.BooleanField(default=False, verbose_name='Falésia')),
                ('bay', models.BooleanField(default=False, verbose_name='Beira Mar')),
                ('trail', models.BooleanField(default=False, verbose_name='Trilha')),
                ('other_accesses', models.CharField(blank=True, default='', max_length=220, verbose_name='Outros acessos')),
                ('rock', models.BooleanField(default=False, verbose_name='Pedra')),
                ('sand', models.BooleanField(default=False, verbose_name='Areia')),
                ('coral', models.BooleanField(default=False, verbose_name='Coral')),
                ('low', models.BooleanField(default=False, verbose_name='Seca')),
                ('high', models.BooleanField(default=False, verbose_name='Cheia')),
                ('ebb', models.BooleanField(default=False, verbose_name='Secando')),
                ('flood', models.BooleanField(default=False, verbose_name='Enchendo')),
                ('right', models.BooleanField(default=False, verbose_name='Direita')),
                ('left', models.BooleanField(default=False, verbose_name='Esquerda')),
                ('beginner', models.BooleanField(default=False, verbose_name='Iniciante')),
                ('intermediate', models.BooleanField(default=False, verbose_name='Intermediário')),
                ('expert', models.BooleanField(default=False, verbose_name='Experiente')),
                ('low_frequency', models.BooleanField(default=False, verbose_name='Frequência baixa')),
                ('regular_frequency', models.BooleanField(default=False, verbose_name='Frequência regular')),
                ('high_frequency', models.BooleanField(default=False, verbose_name='Frequência alta')),
                ('current', models.BooleanField(default=False, verbose_name='Correnteza')),
                ('localism', models.BooleanField(default=False, verbose_name='Localismo')),
                ('boat', models.BooleanField(default=False, verbose_name='Barcos')),
                ('jetski', models.BooleanField(default=False, verbose_name='Jet Ski')),
                ('buoy', models.BooleanField(default=False, verbose_name='Bóias')),
                ('pollution', models.BooleanField(default=False, verbose_name='Poluição')),
                ('rocks', models.BooleanField(default=False, verbose_name='Pedras')),
                ('shark', models.BooleanField(default=False, verbose_name='Tubarões')),
                ('undertow', models.BooleanField(default=False, verbose_name='Ressaca')),
                ('other_dangers', models.CharField(blank=True, default='', max_length=220, verbose_name='Outros perigos')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.Spot', verbose_name='Pico')),
            ],
            options={
                'verbose_name': 'Pico do DicaSurf',
                'verbose_name_plural': 'Picos do DicaSurf',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do estado')),
                ('abbreviation', models.CharField(max_length=2, verbose_name='Sigla do estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título breve')),
                ('thumb', models.ImageField(upload_to='', verbose_name='Arquivo thumb')),
                ('youtube_url', models.URLField(verbose_name='Link do youtube')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.SpotDetail', verbose_name='Detalhamento')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='api.State', verbose_name='Estado'),
        ),
    ]
