# Generated by Django 2.2.5 on 2019-10-03 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotdetail',
            name='spot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.Spot', verbose_name='Pico'),
        ),
    ]
