# Generated by Django 2.2.5 on 2019-09-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título breve')),
                ('thumb', models.FileField(upload_to='', verbose_name='Arquivo thumb')),
                ('youtube_url', models.URLField(verbose_name='Link do youtube')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.Spot', verbose_name='Vídeo')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
            },
        ),
    ]
