# Generated by Django 2.2.5 on 2019-09-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='header_image',
            field=models.FileField(default='', upload_to='', verbose_name='Imagem principal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='info_image',
            field=models.FileField(default='a', upload_to='', verbose_name='Imagem lateral'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.Spot', verbose_name='Pico'),
        ),
    ]
