# Generated by Django 2.2.5 on 2019-09-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190926_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='header_image',
            field=models.ImageField(upload_to='', verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='info_image',
            field=models.ImageField(upload_to='', verbose_name='Imagem lateral'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumb',
            field=models.ImageField(upload_to='', verbose_name='Arquivo thumb'),
        ),
    ]
