# Generated by Django 2.2.5 on 2019-11-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191106_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(default=0, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='lng',
            field=models.FloatField(default=0, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='lat',
            field=models.FloatField(default=0, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='lng',
            field=models.FloatField(default=0, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
