# Generated by Django 2.2.5 on 2019-11-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191118_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Visivel para todos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_text',
            field=models.TextField(max_length=250, verbose_name='Texto de preview'),
        ),
        migrations.AlterField(
            model_name='state',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Visivel para todos'),
        ),
    ]
