# Generated by Django 2.2.5 on 2019-11-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_text',
            field=models.TextField(max_length=450, verbose_name='Texto de preview'),
        ),
    ]
