# Generated by Django 2.2.5 on 2019-11-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191118_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_previews', to='sitemanager.Image', verbose_name='Imagem de preview'),
        ),
        migrations.AlterField(
            model_name='spotdetail',
            name='header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_headers', to='sitemanager.Image', verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='spotdetail',
            name='info_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_infos', to='sitemanager.Image', verbose_name='Imagem lateral'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumb_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='sitemanager.Image', verbose_name='Arquivo thumb'),
        ),
    ]
