# Generated by Django 2.2.5 on 2019-12-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_firstuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstuser',
            options={'verbose_name': 'Usuario pre-registrado', 'verbose_name_plural': 'Usuarios pre-registrados'},
        ),
        migrations.AlterField(
            model_name='firstuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
