# Generated by Django 2.2.5 on 2019-12-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191204_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossiblePartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('choice', models.CharField(choices=[(1, 'Sunrise'), (2, 'Big Rider'), (3, 'Rosa dos Ventos'), (4, 'Adesão Anual')], max_length=15)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Possiveis Parceiros',
            },
        ),
        migrations.AlterModelOptions(
            name='firstuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios pre-registrados'},
        ),
    ]
