# Generated by Django 2.2.5 on 2019-12-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191206_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios pre-registrados (Loja)'},
        ),
        migrations.AlterField(
            model_name='possiblepartner',
            name='choice',
            field=models.CharField(choices=[(1, 'Sunrise'), (2, 'Big Rider'), (3, 'Rosa dos Ventos'), (4, 'Adesão Anual')], max_length=15, verbose_name='Plano'),
        ),
    ]
