# Generated by Django 2.2.5 on 2019-12-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0006_sphereimage'),
        ('api', '0013_auto_20191212_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_five', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_five', to='sitemanager.SphereImage', verbose_name='Imagem 5')),
                ('image_four', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_four', to='sitemanager.SphereImage', verbose_name='Imagem 4')),
                ('image_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_one', to='sitemanager.SphereImage', verbose_name='Imagem 1')),
                ('image_six', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_six', to='sitemanager.SphereImage', verbose_name='Imagem 6')),
                ('image_three', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_three', to='sitemanager.SphereImage', verbose_name='Imagem 3')),
                ('image_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_two', to='sitemanager.SphereImage', verbose_name='Imagem 2')),
            ],
            options={
                'verbose_name': 'Painel',
                'verbose_name_plural': 'Paineis 360',
            },
        ),
    ]
