# Generated by Django 2.2.5 on 2019-12-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191219_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegrid',
            options={'verbose_name': 'Grid 360', 'verbose_name_plural': 'Grids'},
        ),
        migrations.AlterField(
            model_name='imagegrid',
            name='image_five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_five', to='sitemanager.SphereImage', verbose_name='Imagem 5'),
        ),
        migrations.AlterField(
            model_name='imagegrid',
            name='image_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_four', to='sitemanager.SphereImage', verbose_name='Imagem 4'),
        ),
        migrations.AlterField(
            model_name='imagegrid',
            name='image_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_one', to='sitemanager.SphereImage', verbose_name='Imagem 1'),
        ),
        migrations.AlterField(
            model_name='imagegrid',
            name='image_six',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_six', to='sitemanager.SphereImage', verbose_name='Imagem 6'),
        ),
        migrations.AlterField(
            model_name='imagegrid',
            name='image_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_three', to='sitemanager.SphereImage', verbose_name='Imagem 3'),
        ),
        migrations.AlterField(
            model_name='imagegrid',
            name='image_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_two', to='sitemanager.SphereImage', verbose_name='Imagem 2'),
        ),
        migrations.AlterField(
            model_name='imagegrid',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_panel', to='api.SpotDetail', verbose_name='Pico'),
        ),
    ]
