# Generated by Django 2.2.5 on 2019-12-19 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0006_sphereimage'),
        ('api', '0016_auto_20191219_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegrid',
            options={'verbose_name': 'Grid 360 (Imagem)', 'verbose_name_plural': 'Grids (Imagem)'},
        ),
        migrations.AddField(
            model_name='spotdetail',
            name='pictures_gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures_gallery', to='sitemanager.Image', verbose_name='Imagem para a galeria de fotos 360'),
        ),
        migrations.AddField(
            model_name='spotdetail',
            name='videos_gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_gallery', to='sitemanager.Image', verbose_name='Imagem para a galeria de videos 360'),
        ),
    ]
