# Generated by Django 2.2.5 on 2019-12-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_videogrid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegrid',
            options={'verbose_name': 'Grid 360 (Imagem)', 'verbose_name_plural': 'Grids 360 (Imagem)'},
        ),
        migrations.AlterModelOptions(
            name='videogrid',
            options={'verbose_name': 'Grid 360 (Video)', 'verbose_name_plural': 'Grids 360 (Video)'},
        ),
        migrations.AddField(
            model_name='imagegrid',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='videogrid',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
