# Generated by Django 2.2.5 on 2019-12-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191223_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegrid',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='videogrid',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
