# Generated by Django 2.2.5 on 2020-01-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200106_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotdetail',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_headers', to='sitemanager.Image', verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='spotdetail',
            name='pictures_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures_gallery', to='sitemanager.Image', verbose_name='Imagem para a galeria de fotos 360'),
        ),
        migrations.AlterField(
            model_name='spotdetail',
            name='videos_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_gallery', to='sitemanager.Image', verbose_name='Imagem para a galeria de videos 360'),
        ),
    ]
